// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMrX23WidszJCN4JDxdhr4niEr8STPiaU',
    appId: '1:543556718444:web:e628f4c846740561662d49',
    messagingSenderId: '543556718444',
    projectId: 'foode-7ac20',
    authDomain: 'foode-7ac20.firebaseapp.com',
    storageBucket: 'foode-7ac20.firebasestorage.app',
    measurementId: 'G-HHF605T036',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE3qeoNWI7BDzQtNvbKps0DFzgRzhXy3E',
    appId: '1:543556718444:android:d60913d8388fa9c2662d49',
    messagingSenderId: '543556718444',
    projectId: 'foode-7ac20',
    storageBucket: 'foode-7ac20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsNK8RwNoPZCS58O6jpEE68D6REYqoqTU',
    appId: '1:543556718444:ios:9f62ec95b38deb45662d49',
    messagingSenderId: '543556718444',
    projectId: 'foode-7ac20',
    storageBucket: 'foode-7ac20.firebasestorage.app',
    iosBundleId: 'com.foodedelivery.foodeDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsNK8RwNoPZCS58O6jpEE68D6REYqoqTU',
    appId: '1:543556718444:ios:9f62ec95b38deb45662d49',
    messagingSenderId: '543556718444',
    projectId: 'foode-7ac20',
    storageBucket: 'foode-7ac20.firebasestorage.app',
    iosBundleId: 'com.foodedelivery.foodeDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMrX23WidszJCN4JDxdhr4niEr8STPiaU',
    appId: '1:543556718444:web:f0fe8dbf1ee86221662d49',
    messagingSenderId: '543556718444',
    projectId: 'foode-7ac20',
    authDomain: 'foode-7ac20.firebaseapp.com',
    storageBucket: 'foode-7ac20.firebasestorage.app',
    measurementId: 'G-CL1KWERJQ6',
  );
}
